
-- Drop helper functions if they exist
DROP FUNCTION IF EXISTS public.drop_type_if_exists(text, text) CASCADE;

-- Function to safely drop a type if it exists
CREATE OR REPLACE FUNCTION public.drop_type_if_exists(schema_name text, type_name text)
RETURNS void AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE n.nspname = schema_name AND t.typname = type_name) THEN
        EXECUTE 'DROP TYPE ' || quote_ident(schema_name) || '.' || quote_ident(type_name) || ' CASCADE';
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Drop dependent objects and custom types if they exist, in the correct order
DROP FUNCTION IF EXISTS public.get_my_claim(text) CASCADE;
DROP FUNCTION IF EXISTS public.is_admin(text) CASCADE;
DROP FUNCTION IF EXISTS public.on_review_change() CASCADE;
DROP FUNCTION IF EXISTS public.update_activity_rating(uuid) CASCADE;
DROP FUNCTION IF EXISTS public.create_country(text, text, text, text) CASCADE;
DROP FUNCTION IF EXISTS public.update_country(text, text, text, text) CASCADE;
DROP FUNCTION IF EXISTS public.delete_country(text) CASCADE;

SELECT public.drop_type_if_exists('public', 'user_role');
SELECT public.drop_type_if_exists('public', 'activity_status');
SELECT public.drop_type_if_exists('public', 'booking_status');
SELECT public.drop_type_if_exists('public', 'seat_preference_type');
SELECT public.drop_type_if_exists('public', 'referral_status');
SELECT public.drop_type_if_exists('public', 'payout_status');


-- Create custom types
CREATE TYPE public.user_role AS ENUM ('customer', 'admin', 'partner', 'agent');
CREATE TYPE public.activity_status AS ENUM ('pending_approval', 'active', 'inactive', 'rejected');
CREATE TYPE public.booking_status AS ENUM ('pending', 'confirmed', 'cancelled');
CREATE TYPE public.seat_preference_type AS ENUM ('aisle', 'window', 'middle');
CREATE TYPE public.referral_status AS ENUM ('unpaid', 'paid', 'void');
CREATE TYPE public.payout_status AS ENUM ('pending', 'paid', 'failed');


-- Create helper functions for RLS
CREATE OR REPLACE FUNCTION public.get_my_claim(claim TEXT)
RETURNS jsonb
LANGUAGE sql
STABLE
AS $$
  select nullif(current_setting('request.jwt.claims', true), '')::jsonb -> claim
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  select (get_my_claim('role')::text = '"admin"')
$$;


-- Create Tables
CREATE TABLE IF NOT EXISTS public.countries (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL UNIQUE,
    name text NOT NULL UNIQUE,
    currency text NOT NULL,
    currency_symbol text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.cities (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    country_code text NOT NULL REFERENCES public.countries(code) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(country_code, name)
);

CREATE TABLE IF NOT EXISTS public.activity_types (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.partners (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    company_name text NOT NULL,
    contact_email text,
    website text,
    iban text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.activities (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    city text NOT NULL,
    country text NOT NULL,
    description text,
    price numeric(10,2) DEFAULT 0.00 NOT NULL,
    duration text,
    activitytypeid uuid REFERENCES public.activity_types(id) ON DELETE SET NULL,
    partner_id uuid REFERENCES public.partners(id) ON DELETE SET NULL,
    rating numeric(3,2) DEFAULT 0.00 NOT NULL,
    images text[],
    operatinghours text,
    whatsincluded text[],
    whatsnotincluded text[],
    instructions text,
    howtogetthere text,
    additionalinfo text,
    cancellationpolicy text,
    status public.activity_status DEFAULT 'pending_approval'::public.activity_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.bookings (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    guest_email text,
    guest_name text,
    activity_id uuid NOT NULL REFERENCES public.activities(id) ON DELETE CASCADE,
    booking_date timestamp with time zone NOT NULL,
    status public.booking_status DEFAULT 'pending'::public.booking_status NOT NULL,
    quantity integer DEFAULT 1 NOT NULL,
    total_price numeric(10,2) NOT NULL,
    booking_reference text UNIQUE,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.reviews (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    activity_id uuid NOT NULL REFERENCES public.activities(id) ON DELETE CASCADE,
    author text,
    rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(user_id, activity_id)
);

CREATE TABLE IF NOT EXISTS public.wishlist_items (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    activity_id uuid NOT NULL REFERENCES public.activities(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(user_id, activity_id)
);

CREATE TABLE IF NOT EXISTS public.user_documents (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    document_type text NOT NULL,
    file_name text NOT NULL,
    file_path text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.points_history (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    points_change integer NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.agents (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    agency_name text,
    commission_rate numeric(5,2) DEFAULT 5.00 NOT NULL,
    referral_code text NOT NULL UNIQUE,
    paypal_email text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.referrals (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id uuid NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
    agent_id uuid NOT NULL REFERENCES public.agents(id) ON DELETE CASCADE,
    commission_amount numeric(10,2) NOT NULL,
    status public.referral_status DEFAULT 'unpaid'::public.referral_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.payouts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_id uuid NOT NULL REFERENCES public.agents(id) ON DELETE CASCADE,
    amount numeric(10,2) NOT NULL,
    status public.payout_status DEFAULT 'pending'::public.payout_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    paid_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.settings (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    key text NOT NULL UNIQUE,
    value text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


-- Create table indexes
CREATE INDEX IF NOT EXISTS idx_activities_city_country ON public.activities (city, country);
CREATE INDEX IF NOT EXISTS idx_activities_activitytypeid ON public.activities (activitytypeid);
CREATE INDEX IF NOT EXISTS idx_bookings_user_id ON public.bookings (user_id);
CREATE INDEX IF NOT EXISTS idx_bookings_activity_id ON public.bookings (activity_id);
CREATE INDEX IF NOT EXISTS idx_reviews_activity_id ON public.reviews (activity_id);
CREATE INDEX IF NOT EXISTS idx_wishlist_items_user_id ON public.wishlist_items (user_id);


-- Create Functions
CREATE OR REPLACE FUNCTION public.update_activity_rating(p_activity_id uuid)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public.activities
    SET rating = (
        SELECT AVG(r.rating)
        FROM public.reviews r
        WHERE r.activity_id = p_activity_id
    )
    WHERE id = p_activity_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.on_review_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    -- Use PERFORM for side-effect-only function calls in PL/pgSQL
    PERFORM public.update_activity_rating(COALESCE(NEW.activity_id, OLD.activity_id));
    RETURN NULL; -- result is ignored since this is an AFTER trigger
END;
$$;

CREATE OR REPLACE FUNCTION public.create_country(p_code text, p_name text, p_currency text, p_currency_symbol text)
RETURNS void AS $$
BEGIN
  -- Check if country with the same code or name already exists
  IF EXISTS (SELECT 1 FROM public.countries WHERE code = p_code OR name = p_name) THEN
    RAISE EXCEPTION 'A country with this code or name already exists.';
  END IF;

  INSERT INTO public.countries (code, name, currency, currency_symbol)
  VALUES (p_code, p_name, p_currency, p_currency_symbol);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.update_country(p_code text, p_name text, p_currency text, p_currency_symbol text)
RETURNS void AS $$
BEGIN
  -- Check if another country with the new name already exists
  IF EXISTS (SELECT 1 FROM public.countries WHERE name = p_name AND code != p_code) THEN
    RAISE EXCEPTION 'Another country with the name "%" already exists.', p_name;
  END IF;
  
  UPDATE public.countries
  SET 
    name = p_name,
    currency = p_currency,
    currency_symbol = p_currency_symbol
  WHERE code = p_code;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.delete_country(p_code text)
RETURNS void AS $$
BEGIN
    -- Check if the country is linked to any cities
    IF EXISTS (SELECT 1 FROM public.cities WHERE country_code = p_code) THEN
        RAISE EXCEPTION 'Cannot delete country because it is linked to one or more cities.';
    END IF;

    -- If no cities are linked, delete the country
    DELETE FROM public.countries WHERE code = p_code;
END;
$$ LANGUAGE plpgsql;

-- RLS policies
ALTER TABLE public.activity_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlist_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.points_history ENABLE ROW LEVEL SECURITY;


-- Drop existing policies before creating new ones
DROP POLICY IF EXISTS "Enable read access for all users" ON public.activity_types;
CREATE POLICY "Enable read access for all users" ON public.activity_types FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow admin to manage" ON public.activity_types;
CREATE POLICY "Allow admin to manage" ON public.activity_types FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Enable read access for all users" ON public.activities;
CREATE POLICY "Enable read access for all users" ON public.activities FOR SELECT USING (status = 'active');
DROP POLICY IF EXISTS "Allow users to create their own activities" ON public.activities;
CREATE POLICY "Allow users to create their own activities" ON public.activities FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow users to update their own activities" ON public.activities;
CREATE POLICY "Allow users to update their own activities" ON public.activities FOR UPDATE USING (auth.uid() = partner_id);
DROP POLICY IF EXISTS "Allow admin to delete activities" ON public.activities;
CREATE POLICY "Allow admin to delete activities" ON public.activities FOR DELETE USING (public.is_admin());

DROP POLICY IF EXISTS "Allow users to view their own bookings" ON public.bookings;
CREATE POLICY "Allow users to view their own bookings" ON public.bookings FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Allow users to create bookings" ON public.bookings;
CREATE POLICY "Allow users to create bookings" ON public.bookings FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "Allow admin and partners to view bookings" ON public.bookings;
CREATE POLICY "Allow admin and partners to view bookings" ON public.bookings FOR SELECT USING (
    public.is_admin() OR
    (get_my_claim('role')::text = '"partner"' AND activity_id IN (SELECT id FROM activities WHERE partner_id = auth.uid()))
);

DROP POLICY IF EXISTS "Enable read access for all users" ON public.reviews;
CREATE POLICY "Enable read access for all users" ON public.reviews FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow users to create reviews" ON public.reviews;
CREATE POLICY "Allow users to create reviews" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Allow users to manage their own reviews" ON public.reviews;
CREATE POLICY "Allow users to manage their own reviews" ON public.reviews FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow users to manage their own wishlist" ON public.wishlist_items;
CREATE POLICY "Allow users to manage their own wishlist" ON public.wishlist_items FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Partners can view their own profile" ON public.partners;
CREATE POLICY "Partners can view their own profile" ON public.partners FOR SELECT USING (auth.uid() = id);
DROP POLICY IF EXISTS "Partners can update their own profile" ON public.partners;
CREATE POLICY "Partners can update their own profile" ON public.partners FOR UPDATE USING (auth.uid() = id);
DROP POLICY IF EXISTS "Admins can manage all partner profiles" ON public.partners;
CREATE POLICY "Admins can manage all partner profiles" ON public.partners FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Agents can view their own profile" ON public.agents;
CREATE POLICY "Agents can view their own profile" ON public.agents FOR SELECT USING (auth.uid() = id);
DROP POLICY IF EXISTS "Agents can update their own profile" ON public.agents;
CREATE POLICY "Agents can update their own profile" ON public.agents FOR UPDATE USING (auth.uid() = id);
DROP POLICY IF EXISTS "Admins can manage all agent profiles" ON public.agents;
CREATE POLICY "Admins can manage all agent profiles" ON public.agents FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Agents can view their own referrals" ON public.referrals;
CREATE POLICY "Agents can view their own referrals" ON public.referrals FOR SELECT USING (auth.uid() = agent_id);
DROP POLICY IF EXISTS "Admins can manage all referrals" ON public.referrals;
CREATE POLICY "Admins can manage all referrals" ON public.referrals FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Agents can view their own payouts" ON public.payouts;
CREATE POLICY "Agents can view their own payouts" ON public.payouts FOR SELECT USING (auth.uid() = agent_id);
DROP POLICY IF EXISTS "Admins can manage all payouts" ON public.payouts;
CREATE POLICY "Admins can manage all payouts" ON public.payouts FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Enable read access for all users" ON public.settings;
CREATE POLICY "Enable read access for all users" ON public.settings FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow admins to manage settings" ON public.settings;
CREATE POLICY "Allow admins to manage settings" ON public.settings FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Users can manage their own documents" ON public.user_documents;
CREATE POLICY "Users can manage their own documents" ON public.user_documents FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own points history" ON public.points_history;
CREATE POLICY "Users can view their own points history" ON public.points_history FOR SELECT USING (auth.uid() = user_id);

-- Triggers
DROP TRIGGER IF EXISTS on_review_change_trigger ON public.reviews;
CREATE TRIGGER on_review_change_trigger
AFTER INSERT OR UPDATE OR DELETE ON public.reviews
FOR EACH ROW EXECUTE FUNCTION public.on_review_change();
