
-- Drop helper function if it exists
DROP FUNCTION IF EXISTS public.drop_type_if_exists(text, text) CASCADE;

-- Function to safely drop a type if it exists
CREATE OR REPLACE FUNCTION public.drop_type_if_exists(schema_name text, type_name text)
RETURNS void AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON t.typnamespace = n.oid WHERE n.nspname = schema_name AND t.typname = type_name) THEN
        EXECUTE 'DROP TYPE ' || quote_ident(schema_name) || '.' || quote_ident(type_name) || ' CASCADE';
    END IF;
END;
$$ LANGUAGE plpgsql;


-- Drop types if they exist to ensure idempotency
SELECT public.drop_type_if_exists('public', 'user_role');
SELECT public.drop_type_if_exists('public', 'activity_status');
SELECT public.drop_type_if_exists('public', 'booking_status');
SELECT public.drop_type_if_exists('public', 'referral_status');
SELECT public.drop_type_if_exists('public', 'payout_status');

-- Create ENUM types
CREATE TYPE public.user_role AS ENUM ('customer', 'agent', 'partner', 'admin');
CREATE TYPE public.activity_status AS ENUM ('pending_approval', 'active', 'inactive', 'rejected');
CREATE TYPE public.booking_status AS ENUM ('pending', 'confirmed', 'cancelled');
CREATE TYPE public.referral_status AS ENUM ('paid', 'unpaid');
CREATE TYPE public.payout_status AS ENUM ('pending', 'paid', 'failed');


-- Drop existing tables with CASCADE to remove dependencies
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.wishlist_items CASCADE;
DROP TABLE IF EXISTS public.bookings CASCADE;
DROP TABLE IF EXISTS public.activities CASCADE;
DROP TABLE IF EXISTS public.activity_types CASCADE;
DROP TABLE IF EXISTS public.cities CASCADE;
DROP TABLE IF EXISTS public.countries CASCADE;
DROP TABLE IF EXISTS public.partners CASCADE;
DROP TABLE IF EXISTS public.agents CASCADE;
DROP TABLE IF EXISTS public.referrals CASCADE;
DROP TABLE IF EXISTS public.payouts CASCADE;
DROP TABLE IF EXISTS public.user_documents CASCADE;
DROP TABLE IF EXISTS public.points_history CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;


-- Create Countries Table
CREATE TABLE public.countries (
    id bigint generated by default as identity primary key,
    code character(2) not null unique,
    name text not null unique,
    currency character(3) not null,
    currency_symbol text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
COMMENT ON TABLE public.countries IS 'Stores country information.';

-- Create Cities Table
CREATE TABLE public.cities (
    id bigint generated by default as identity primary key,
    name text not null,
    country_code character(2) not null references public.countries(code) ON DELETE CASCADE,
    unique (name, country_code),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
COMMENT ON TABLE public.cities IS 'Stores cities associated with countries.';

-- Create Activity Types Table
CREATE TABLE public.activity_types (
    id uuid not null default gen_random_uuid() primary key,
    name text not null unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
COMMENT ON TABLE public.activity_types IS 'Categories for activities, e.g., Tour, Museum Visit.';

-- Create Partners Table
CREATE TABLE public.partners (
    id uuid not null primary key references auth.users(id) ON DELETE CASCADE,
    company_name text not null,
    contact_email text,
    website text,
    iban text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
COMMENT ON TABLE public.partners IS 'Tour operators or providers of excursions.';

-- Create Agents Table
CREATE TABLE public.agents (
    id uuid not null primary key references auth.users(id) ON DELETE CASCADE,
    agency_name text,
    commission_rate numeric(5, 2) not null default 5.0,
    referral_code text not null unique,
    paypal_email text,
    sponsor_id uuid references auth.users(id),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
COMMENT ON TABLE public.agents IS 'Affiliate agents who refer customers.';


-- Create Activities Table
CREATE TABLE public.activities (
    id uuid not null default gen_random_uuid() primary key,
    name text not null,
    city text not null,
    country text not null,
    description text,
    price numeric(10, 2) not null default 0.00,
    duration text,
    activitytypeid uuid references public.activity_types(id),
    partner_id uuid null references public.partners(id) ON DELETE SET NULL,
    rating numeric(3, 2) not null default 0.00,
    images text[],
    operatinghours text,
    whatsincluded text[],
    whatsnotincluded text[],
    instructions text,
    howtogetthere text,
    additionalinfo text,
    cancellationpolicy text,
    status activity_status not null default 'pending_approval',
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
COMMENT ON TABLE public.activities IS 'Stores all excursions and tours.';


-- Create Bookings Table
CREATE TABLE public.bookings (
    id uuid not null default gen_random_uuid() primary key,
    user_id uuid null references auth.users(id) ON DELETE SET NULL,
    activity_id uuid not null references public.activities(id) ON DELETE CASCADE,
    booking_date timestamp with time zone not null,
    status booking_status not null default 'confirmed',
    quantity integer not null default 1,
    total_price numeric(10, 2) not null,
    booking_reference text not null unique,
    guest_email text,
    guest_name text,
    created_at timestamp with time zone not null default now()
);
COMMENT ON TABLE public.bookings IS 'Stores user bookings for activities.';
CREATE INDEX bookings_user_id_idx ON public.bookings (user_id);
CREATE INDEX bookings_activity_id_idx ON public.bookings (activity_id);


-- Create Reviews Table
CREATE TABLE public.reviews (
    id uuid not null default gen_random_uuid() primary key,
    user_id uuid not null references auth.users(id) ON DELETE CASCADE,
    activity_id uuid not null references public.activities(id) ON DELETE CASCADE,
    rating integer not null check (rating >= 1 and rating <= 5),
    comment text,
    author text,
    created_at timestamp with time zone not null default now(),
    unique (user_id, activity_id)
);
COMMENT ON TABLE public.reviews IS 'Stores user reviews for activities.';


-- Create Wishlist Table
CREATE TABLE public.wishlist_items (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) ON DELETE CASCADE,
    activity_id uuid not null references public.activities(id) ON DELETE CASCADE,
    created_at timestamp with time zone not null default now(),
    unique(user_id, activity_id)
);
COMMENT ON TABLE public.wishlist_items IS 'Stores items in a user''s wishlist.';

-- Create Referrals Table
CREATE TABLE public.referrals (
    id uuid not null default gen_random_uuid() primary key,
    booking_id uuid not null unique references public.bookings(id) ON DELETE CASCADE,
    agent_id uuid not null references public.agents(id) ON DELETE CASCADE,
    commission_amount numeric(10, 2) not null,
    status referral_status not null default 'unpaid',
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
COMMENT ON TABLE public.referrals IS 'Tracks commissions for agent referrals.';

-- Create Payouts Table
CREATE TABLE public.payouts (
    id uuid not null default gen_random_uuid() primary key,
    agent_id uuid not null references public.agents(id) ON DELETE CASCADE,
    amount numeric(10, 2) not null,
    status payout_status not null default 'pending',
    created_at timestamp with time zone not null default now(),
    paid_at timestamp with time zone
);
COMMENT ON TABLE public.payouts IS 'Tracks payouts made to agents.';

-- Create User Documents Table
CREATE TABLE public.user_documents (
    id uuid not null default gen_random_uuid() primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    document_type text not null,
    file_name text not null,
    file_path text not null unique,
    created_at timestamp with time zone not null default now()
);
COMMENT ON TABLE public.user_documents IS 'Securely stores user travel documents.';

-- Create Points History Table
CREATE TABLE public.points_history (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    points_change integer not null,
    description text,
    created_at timestamp with time zone not null default now()
);
COMMENT ON TABLE public.points_history IS 'Logs changes to user loyalty points.';

-- Create Settings Table
CREATE TABLE public.settings (
    id bigint generated by default as identity primary key,
    key text not null unique,
    value jsonb,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
COMMENT ON TABLE public.settings IS 'Stores general application settings.';



-- ======== HELPER FUNCTIONS AND TRIGGERS ======== --

-- Drop existing functions with CASCADE to remove dependencies
DROP FUNCTION IF EXISTS public.get_my_claim(text) CASCADE;
DROP FUNCTION IF EXISTS public.is_claims_admin() CASCADE;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.handle_review_change() CASCADE;
DROP FUNCTION IF EXISTS public.update_activity_rating(uuid) CASCADE;
DROP FUNCTION IF EXISTS public.create_country(character, text, character, text) CASCADE;
DROP FUNCTION IF EXISTS public.update_country(character, text, character, text) CASCADE;
DROP FUNCTION IF EXISTS public.delete_country(character) CASCADE;

-- Function to get a claim from the JWT
CREATE OR REPLACE FUNCTION public.get_my_claim(claim TEXT)
RETURNS JSONB AS $$
  SELECT COALESCE(current_setting('request.jwt.claims', true)::JSONB ->> claim, NULL)::JSONB;
$$ LANGUAGE SQL STABLE;

-- Function to check if the user is an admin based on the JWT claim
CREATE OR REPLACE FUNCTION public.is_claims_admin()
RETURNS BOOLEAN AS $$
  SELECT COALESCE((get_my_claim('role'))::text = '"admin"', false);
$$ LANGUAGE SQL STABLE;

-- Trigger function to automatically create a profile for new users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  user_role TEXT;
BEGIN
  user_role := COALESCE((new.raw_user_meta_data->>'role')::text, 'customer');

  IF user_role = 'partner' THEN
    INSERT INTO public.partners (id, company_name, contact_email)
    VALUES (new.id, COALESCE(new.raw_user_meta_data->>'full_name', 'Unnamed Partner'), new.email);
  ELSIF user_role = 'agent' THEN
    INSERT INTO public.agents (id, agency_name, commission_rate, referral_code)
    VALUES (new.id, COALESCE(new.raw_user_meta_data->>'full_name', 'Unnamed Agent'), 5.0, 'AGENT' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
  END IF;
  
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- Function to update the average rating of an activity
CREATE OR REPLACE FUNCTION public.update_activity_rating(p_activity_id uuid)
RETURNS void AS $$
DECLARE
    avg_rating numeric;
BEGIN
    -- Calculate the average rating from the reviews for the given activity
    SELECT AVG(rating) INTO avg_rating
    FROM public.reviews
    WHERE activity_id = p_activity_id;

    -- Update the activities table with the new average rating
    UPDATE public.activities
    SET rating = COALESCE(avg_rating, 0)
    WHERE id = p_activity_id;
END;
$$ LANGUAGE plpgsql;


-- Trigger function that calls update_activity_rating on any change to reviews
CREATE OR REPLACE FUNCTION public.handle_review_change()
RETURNS TRIGGER AS $$
DECLARE
    v_activity_id uuid;
BEGIN
    IF (TG_OP = 'DELETE') THEN
        v_activity_id := OLD.activity_id;
    ELSE
        v_activity_id := NEW.activity_id;
    END IF;

    -- Perform the rating update in a separate function call
    PERFORM public.update_activity_rating(v_activity_id);
    
    RETURN NULL; -- result is ignored since this is an AFTER trigger
END;
$$ LANGUAGE plpgsql;


-- Function to create a country and a city
CREATE OR REPLACE FUNCTION public.create_country(
    p_code character(2),
    p_name text,
    p_currency character(3),
    p_currency_symbol text
) RETURNS void AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.countries WHERE code = p_code OR name = p_name) THEN
        RAISE EXCEPTION 'A country with this code or name already exists.';
    END IF;
    INSERT INTO public.countries (code, name, currency, currency_symbol)
    VALUES (p_code, p_name, p_currency, p_currency_symbol);
END;
$$ LANGUAGE plpgsql;

-- Function to update a country
CREATE OR REPLACE FUNCTION public.update_country(
    p_code character(2),
    p_name text,
    p_currency character(3),
    p_currency_symbol text
) RETURNS void AS $$
BEGIN
    UPDATE public.countries
    SET name = p_name, currency = p_currency, currency_symbol = p_currency_symbol, updated_at = now()
    WHERE code = p_code;
END;
$$ LANGUAGE plpgsql;

-- Function to delete a country
CREATE OR REPLACE FUNCTION public.delete_country(p_code character(2))
RETURNS void AS $$
BEGIN
    DELETE FROM public.countries WHERE code = p_code;
END;
$$ LANGUAGE plpgsql;


-- ======== TRIGGERS ======== --

-- Drop triggers if they exist
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP TRIGGER IF EXISTS on_review_change ON public.reviews;


-- Trigger for new user creation
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
  
-- Trigger for review changes
CREATE TRIGGER on_review_change
  AFTER INSERT OR UPDATE OR DELETE ON public.reviews
  FOR EACH ROW EXECUTE FUNCTION public.handle_review_change();


-- ======== ROW LEVEL SECURITY (RLS) POLICIES ======== --

-- Enable RLS for all tables
ALTER TABLE public.countries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlist_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.points_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;


-- Drop existing policies
DROP POLICY IF EXISTS "Enable read access for all users" ON public.countries;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.cities;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.activity_types;
DROP POLICY IF EXISTS "Allow admin to manage" ON public.activity_types;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.activities;
DROP POLICY IF EXISTS "Allow users to create their own activities" ON public.activities;
DROP POLICY IF EXISTS "Allow users to update their own activities" ON public.activities;
DROP POLICY IF EXISTS "Allow admin to delete activities" ON public.activities;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.reviews;
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.reviews;
DROP POLICY IF EXISTS "Enable read access for own wishlist items" ON public.wishlist_items;
DROP POLICY IF EXISTS "Enable all operations for own wishlist items" ON public.wishlist_items;
DROP POLICY IF EXISTS "Enable read access for user's own bookings" ON public.bookings;
DROP POLICY IF EXISTS "Allow users to create their own bookings" ON public.bookings;
DROP POLICY IF EXISTS "Allow admin and partners to view bookings" ON public.bookings;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.partners;
DROP POLICY IF EXISTS "Admins can manage all partner profiles" ON public.partners;
DROP POLICY IF EXISTS "Partners can view and edit their own profile" ON public.partners;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.agents;
DROP POLICY IF EXISTS "Admins can manage all agent profiles" ON public.agents;
DROP POLICY IF EXISTS "Agents can view and edit their own profile" ON public.agents;
DROP POLICY IF EXISTS "Enable all operations for own documents" ON public.user_documents;
DROP POLICY IF EXISTS "Enable read access for own points history" ON public.points_history;
DROP POLICY IF EXISTS "Agents can see their own referrals" ON public.referrals;
DROP POLICY IF EXISTS "Admins can manage all referrals" ON public.referrals;
DROP POLICY IF EXISTS "Agents can see their own payouts" ON public.payouts;
DROP POLICY IF EXISTS "Admins can manage all payouts" ON public.payouts;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.settings;
DROP POLICY IF EXISTS "Allow admins to manage settings" ON public.settings;


-- Countries: Publicly readable
CREATE POLICY "Enable read access for all users" ON public.countries FOR SELECT USING (true);

-- Cities: Publicly readable
CREATE POLICY "Enable read access for all users" ON public.cities FOR SELECT USING (true);

-- Activity Types: Publicly readable, admin managed
CREATE POLICY "Enable read access for all users" ON public.activity_types FOR SELECT USING (true);
CREATE POLICY "Allow admin to manage" ON public.activity_types FOR ALL USING (public.is_claims_admin()) WITH CHECK (public.is_claims_admin());

-- Activities: Publicly readable for active, managed by owner/admin
CREATE POLICY "Enable read access for all users" ON public.activities FOR SELECT USING (status = 'active');
CREATE POLICY "Allow users to create their own activities" ON public.activities FOR INSERT WITH CHECK (auth.uid() = partner_id OR (get_my_claim('role'))::text = '"admin"');
CREATE POLICY "Allow users to update their own activities" ON public.activities FOR UPDATE USING (auth.uid() = partner_id OR (get_my_claim('role'))::text = '"admin"') WITH CHECK (auth.uid() = partner_id OR (get_my_claim('role'))::text = '"admin"');
CREATE POLICY "Allow admin to delete activities" ON public.activities FOR DELETE USING (public.is_claims_admin());

-- Reviews: Publicly readable, insert by authenticated
CREATE POLICY "Enable read access for all users" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON public.reviews FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Wishlist: User-specific access
CREATE POLICY "Enable read access for own wishlist items" ON public.wishlist_items FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable all operations for own wishlist items" ON public.wishlist_items FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Bookings: User and admin/partner access
CREATE POLICY "Enable read access for user's own bookings" ON public.bookings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Allow users to create their own bookings" ON public.bookings FOR INSERT WITH CHECK (auth.uid() = user_id OR auth.role() = 'authenticated');
CREATE POLICY "Allow admin and partners to view bookings" ON public.bookings FOR SELECT USING ((get_my_claim('role'))::text = '"admin"' OR EXISTS (SELECT 1 FROM public.activities WHERE public.activities.id = activity_id AND public.activities.partner_id = auth.uid()));

-- Partners: Publicly readable, managed by owner/admin
CREATE POLICY "Enable read access for all users" ON public.partners FOR SELECT USING (true);
CREATE POLICY "Admins can manage all partner profiles" ON public.partners FOR ALL USING (public.is_claims_admin());
CREATE POLICY "Partners can view and edit their own profile" ON public.partners FOR ALL USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- Agents: Publicly readable, managed by owner/admin
CREATE POLICY "Enable read access for all users" ON public.agents FOR SELECT USING (true);
CREATE POLICY "Admins can manage all agent profiles" ON public.agents FOR ALL USING (public.is_claims_admin());
CREATE POLICY "Agents can view and edit their own profile" ON public.agents FOR ALL USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- User Documents: Strictly private
CREATE POLICY "Enable all operations for own documents" ON public.user_documents FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Points History: Strictly private
CREATE POLICY "Enable read access for own points history" ON public.points_history FOR SELECT USING (auth.uid() = user_id);

-- Referrals: Private to agent or admin
CREATE POLICY "Agents can see their own referrals" ON public.referrals FOR SELECT USING (agent_id = auth.uid());
CREATE POLICY "Admins can manage all referrals" ON public.referrals FOR ALL USING (public.is_claims_admin());

-- Payouts: Private to agent or admin
CREATE POLICY "Agents can see their own payouts" ON public.payouts FOR SELECT USING (agent_id = auth.uid());
CREATE POLICY "Admins can manage all payouts" ON public.payouts FOR ALL USING (public.is_claims_admin());

-- Settings: Publicly readable, admin managed
CREATE POLICY "Enable read access for all users" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Allow admins to manage settings" ON public.settings FOR ALL USING (public.is_claims_admin());
